create table weather
(
    id                 int generated by default as identity primary key,
    measurement_time   timestamp not null,
    temperature        float   not null,
    temperature_feels  float   not null,
    weather_icon       varchar not null,
    weather_condition  varchar not null,
    phenom_icon        varchar,
    phenom_condition   varchar,
    wind_speed         float   not null,
    wind_gust          float   not null,
    wind_direction     float   not null,
    pressure_mm        float   not null,
    pressure_pa        float   not null,
    humidity           float   not null,
    is_thunder         boolean not null,
    precision_type     varchar not null,
    precision_strength varchar not null,
    cloudness          varchar not null
)