create table channels
(
    id int generated by default as identity primary key,
    channel_id bigint unique not null,
    channel_name varchar(100)
);

insert into channels(channel_id, channel_name) values (-1002618924720, 'MyWeatherChannel');